<a href="https://colab.research.google.com/github/Zaxzz/kecerdasan_buatan/blob/main/OperasiMTK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 2

# OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA

## 2.	Operasi matematika menggunakan python

In [3]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x, y)

5 18


In [4]:
x = abs(-7.25)
print(x)

7.25


In [5]:
import math
x = math.pow(4, 3)
print(x)

64.0


In [6]:
import math
x = math.sqrt(64)
print(x)

8.0


In [7]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x,y)

2 1


In [8]:
import math
x = math.pi
print(x)

3.141592653589793


## 3.	Menggunakan Fungsi MATH

In [10]:
import math

angka = 10

print("sin(10)       :", math.sin(angka))
print("cos(10)       :", math.cos(angka))
print("tan(10)       :", math.tan(angka))
print("log(10)       :", math.log(angka))
print("log10(10)     :", math.log10(angka))
print("degrees(10)   :", math.degrees(angka))
print("factorial(10) :", math.factorial(angka))
print("fmod(10, 3)   :", math.fmod(angka, 3))
print("gamma(10)     :", math.gamma(angka))
print("perm(10, 3)   :", math.perm(10, 3))
print("dist((0,0) ke (10,10)) :", math.dist([0, 0], [10, 10]))
print("isnan(float('nan')) :", math.isnan(float('nan')))


sin(10)       : -0.5440211108893698
cos(10)       : -0.8390715290764524
tan(10)       : 0.6483608274590866
log(10)       : 2.302585092994046
log10(10)     : 1.0
degrees(10)   : 572.9577951308232
factorial(10) : 3628800
fmod(10, 3)   : 1.0
gamma(10)     : 362880.0
perm(10, 3)   : 720
dist((0,0) ke (10,10)) : 14.142135623730951
isnan(float('nan')) : True


## 4.	Operasi matriks dan vektor dengan python

In [13]:
import numpy as np

A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B

print("Matriks A:")
print(A)

print("\nMatriks B:")
print(B)

print("\nHasil Penjumlahan A + B:")
print(hasil)


Matriks A:
[[80 30 25]
 [50 20 10]]

Matriks B:
[[30 60 15]
 [10 30 30]]

Hasil Penjumlahan A + B:
[[110  90  40]
 [ 60  50  40]]


In [16]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil Dot Product A • B:", hasil)


Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil Dot Product A • B: 2025


In [18]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil Cross Product A × B:", Hasil)


Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil Cross Product A × B: [-305 -110  350]


## Tugas Praktikum

In [21]:
import numpy as np

A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])

AxB = np.dot(A, B)
BxC = np.dot(B, C)

print("Matriks A:")
print(A)

print("\nMatriks B:")
print(B)

print("\nMatriks C:")
print(C)

print("\nHasil A × B:")
print(AxB)

print("\nHasil B × C:")
print(BxC)


Matriks A:
[[3 1]
 [2 0]]

Matriks B:
[[ 2  1]
 [ 1 -1]]

Matriks C:
[[-1  1  2]
 [ 2  0 -1]]

Hasil A × B:
[[7 2]
 [4 2]]

Hasil B × C:
[[ 0  2  3]
 [-3  1  3]]


In [22]:
import math

a = math.factorial(6)
b = math.factorial(8) / math.factorial(5)

print("a. 6! =", a)
print("b. 8! / 5! =", b)


a. 6! = 720
b. 8! / 5! = 336.0


In [25]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

dot_product = np.dot(A, B)

cross_product = np.cross(A, B)

print("Panjang Vektor A:", round(magnitude_A, 2))
print("Panjang Vektor B:", round(magnitude_B, 2))
print("\nHasil Perkalian Titik (A . B):", dot_product)
print("\nHasil Perkalian Silang (A × B):", cross_product)


Panjang Vektor A: 9.11
Panjang Vektor B: 12.41

Hasil Perkalian Titik (A . B): 58

Hasil Perkalian Silang (A × B): [ 24  79 -51]
